services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    env_file: .envs/prod.env
    depends_on:
      - db
  db:
    image: postgres
    env_file: .envs/prod.env
  auth:
    build:
      context: nodejs-recruitment-task/
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      JWT_SECRET: ${JWT_SECRET}
