FROM node:16-alpine
WORKDIR /app
COPY package.json package.json
COPY package-lock.json package-lock.json
RUN npm install
COPY prisma/ prisma/
RUN npx prisma generate
COPY ./ ./
CMD ["npm", "run", "test"]
