version: "3.2"
services:
  app:
    command: node src/server.js
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - published: 3000
        target: 3000
    environment:
      JWT_SECRET: a1b2c3d4
